/*
 * FaultIDs.h
 *
 *  Created on: Mar 27, 2017
 *      Author: rmurshed
 */

#ifndef FAULTIDS_H_
#define FAULTIDS_H_

/* The definition of Layer for Alarm handling */
typedef enum
{
    almChassisLayer,
    almModuleLayer,
    almXCVRLayer,
    almPTPLayer,
    almOTUCnLayer,           /* Optical Transport Unit */
    almODUCnLayer,           /* Optical Data Unit */
    almOTUkLayer,
    almODUkLayer,      /* Optical Payload Unit */
    almPortLayer,
    almServiceLayer,
} alarmLayer;


enum almL0FaultIDs
{
	//Chassis Faults
	WS_OVER_TEMPERATURE_ID = 1,
	WS_UNDER_TEMPERATURE_ID = 2,
	WS_DISK_FULL_ID = 3,
	WS_SOFTWARE_SUBSYSTEM_FAILED_ID = 4,
	WS_UPGRADE_IN_PROGRESS_ID = 5,
	WS_UPGRADE_DOWNLOAD_FAILED_ID = 6,
	WS_UPGRADE_INSTALLATION_FAILED_ID = 7,
	WS_UPGRADE_ACTIVATION_FAILED_ID = 8,
	WS_UPGRADE_COMMIT_FAILED_ID = 9,
	WS_UPGRADE_CANCEL_FAILED_ID = 10,
	WS_POWER_SUPPLY_UNIT_MISSING_ID = 11,
	WS_POWER_SUPPLY_UNIT_FAILED_ID = 12,
	WS_POWER_SUPPLY_FEED_FAILED_ID = 13,
	WS_CHASSIS_LAYER_FAULT_ID = 0,

	//Module Faults
	WS_MODULE_MISSING_ID = 1,
	WS_MODULE_FAILED_ID = 2,
	WS_MODULE_OVER_TEMPERTURE_ID = 3,
	WS_MODULE_OVER_TEMPERTURE_WARNING_ID = 4,
	WS_MODULE_PROVISIONING_MISMATCH_ID = 5,
	WS_MODULE_COMMUNICATIONS_SUSPECTED_ID = 6,
	WS_MODULE_LAYER_FAULT_ID = 0,

	//XCVR Faults
	WS_XCVR_MISSING_ID = 1,
	WS_XCVR_CAPABILITY_MISMATCH_ID = 2,
	WS_XCVR_PROVISIONING_MISMATCH_ID = 3,
	WS_XCVR_FAILED_ID = 4,
	WS_XCVR_OVER_TEMPERATURE_ID = 5,
	WS_XCVR_UNDER_TEMPERATURE_ID = 6,
	WS_XCVR_NOT_PROVISIONED_ID = 7,
	WS_XCVR_NOT_SUPPORTED_ID = 8,
	WS_XCVR_COMMUNICATIONS_SUSPECT_ID = 9,
	WS_XCVR_LAYER_FAULT_ID = 0,



	//PTP Faults
	WS_PTP_LOSS_OF_SIGNAL_ID = 1 ,
	WS_RX_POWER_LOW_ID = 2 ,
	WS_PTP_FREQUENCY_OUT_OF_RANGE_ID = 3 ,
	WS_RX_POWER_HIGH_ID = 4 ,
	WS_LOSS_OF_CHANNEL_ID = 5 ,
	WS_RX_CHANNEL_POWER_LOW_ID = 6 ,
	WS_RX_CHANNEL_POWER_HIGH_ID = 7 ,
	WS_PTP_LOSS_OF_CLOCK_ID = 8 ,
	WS_TX_CHANNEL_CONTENTION_ID = 9 ,
	WS_LOSS_OF_FRAME_ID = 10 ,
	WS_PTP_PRE_FEC_SIGNAL_DEGRADE_ID = 11 ,
	WS_PTP_PRE_FEC_SIGNAL_FAIL_ID = 12 ,
	WS_LOSS_OF_MULTIFRAME_ID = 13 ,
	WS_RDI_ID = 14 ,
	WS_GID_MISMATCH_ID = 15 ,
	WS_PHY_MAP_MISMATCH_ID = 16 ,
	WS_FREQUENCY_PROVISIONING_MISMATCH_ID = 17 ,
	WS_MODEM_CLASS_MISMATCH_ID = 18 ,
	WS_REACH_VIOLATION_ID = 19 ,
	WS_TX_TUNING_IN_PROGRESS_ID = 20 ,
	WS_TX_PROVISIONING_REQUIRED_ID = 21 ,
	WS_TX_POWER_REDUCTION_ID = 22 ,
	WS_TX_POWER_LOW_ID = 23 ,
	WS_TX_POWER_HIGH_ID = 24 ,
	WS_TX_ECHO_TRACE_MISMATCH_ID = 25 ,
	WS_DUPLICATE_ADJACENCY_DISCOVERED_ID = 26 ,
	WS_CHANNEL_CONTENTION_AND_PROVISIONING_REQUIRED_ID =27,
	WS_PTP_LAYER_FAULT_ID = 0 ,

	//OTUCN Faults
	WS_OTUCN_LOSS_OF_LANE_ALIGNMENT_ID = 1,
	WS_OTUCN_LOSS_OF_FRAME_AND_MULTIFRAME_ID = 2,
	WS_OTUCN_FREQUENCY_OUT_OF_RANGE_ID = 3,
	WS_OTU_AIS_ID = 4,
	WS_OTUCN_TRACE_IDENTIFIER_MISMATCH_ID = 5,
	WS_OTUCN_SIGNAL_DEGRADE_ID = 6,
	WS_OTUCN_BDI_ID = 7,
	WS_OTUCN_LOSS_OF_CLOCK_ID = 8,
	WS_OTUCN_LAYER_FAULT_ID = 0,

	//ODUCN Faults
	WS_ODUCN_SIGNAL_FAIL_ID = 1,
	WS_ODUCN_TRACE_IDENTIFIER_MISMATCH_ID = 2,
	WS_LOSS_OF_OPU_MULTIFRAME_IDENTIFIER_ID = 3,
	WS_ODUCN_SIGNAL_DEGRADE_ID = 4,
	WS_ODUCN_AIS_ID = 5,
	WS_ODUCN_LCK_ID = 6,
	WS_ODUCN_BDI_ID = 7,
	WS_MSI_MISMATCH_ID = 8,
	WS_OPU_ODUCN_PAYLOAD_TYPE_MISMATCH_ID = 9,
	WS_ODUCN_STATUS_FAULT_ID = 10,    //Dummy Faults for AIS | LCK
	WS_ODUCN_LAYER_FAULT_ID = 0,


	//ODUK Faults
	WS_ODUK_SIGNAL_FAIL_ID = 1,
	WS_ODUK_LOSS_OF_FRAME_AND_MULTIFRAME_ID = 2,
	WS_ODUK_FREQUENCY_OUT_OF_RANGE_ID = 3,
	WS_ODUK_SIGNAL_DEGRADE_ID = 4,
	WS_ODUK_AIS_ID = 5,
	WS_ODUK_LCK_ID = 6,
	WS_ODUK_BDI_ID = 7,
	WS_ODUK_LOSS_OF_CLOCK_ID = 8,
	WS_OPU_ODUK_PAYLOAD_TYPE_MISMATCH_ID = 9,
	WS_OPU_CSF_ID = 10,
	WS_ODU_OCI_ID = 11,
	WS_ODUK_TRACE_IDENTIFIER_MISMATCH_ID = 12,
	WS_ODUK_STATUS_FAULT_ID = 13,
	WS_ODUK_LAYER_FAULT_ID = 0,

	//OTUK Faults
	WS_OTUK_LOSS_OF_SIGNAL_ID = 1,
	WS_OTUK_LOSS_OF_FRAME_AND_MULTIFRAME_ID = 2,
	WS_OTUK_FREQUENCY_OUT_OF_RANGE_ID = 3,
	WS_OTUK_LOSS_OF_LANE_ALIGNMENT_ID = 4,
	WS_OTUK_SKEW_OUT_OF_RANGE_ID = 5,
	WS_OTUK_AIS_ID = 6,
	WS_OTUK_BDI_ID = 7,
	WS_OTUK_LOSS_OF_CLOCK_ID = 8,
	WS_OTUK_TRACE_IDENTIFIER_MISMATCH_ID = 9,
	WS_OTU_SIGNAL_DEGRADE_ID = 10,
	WS_OTUK_PRE_FEC_SIGNAL_DEGRADE_ID = 11,
	WS_OTUK_PRE_FEC_SIGNAL_FAIL_ID = 12,
	WS_OTUK_TX_LOSS_OF_CLOCK_ID = 13,
	WS_OTUK_TX_FREQUENCY_OUT_OF_RANGE_ID = 14,
	WS_OTUK_LAYER_FAULT_ID = 0,

	//PORT  faults
	WS_ETH_LOSS_OF_SIGNAL_ID = 1,
	WS_LOSS_OF_ALIGNMENT_MARKER_ID = 2,
	WS_ETH_FREQUENCY_OUT_OF_RANGE_ID = 3,
	WS_EXCESSIVE_ERROR_RATIO_ID = 4,
	WS_ETH_SKEW_OUT_OF_RANGE_ID = 5,
	WS_ETH_TX_FREQUENCY_OUT_OF_RANGE_ID = 6,
	WS_PRE_FEC_SIGNAL_DEGRADE_ID = 7,
	WS_ETH_LOSS_OF_CLOCK_ID = 8,
	WS_LOCAL_FAULT_ID = 9,
	WS_REMOTE_FAULT_ID = 10,
	WS_ETH_TX_LOSS_OF_CLOCK_ID = 11,
	WS_ETH_PRE_FEC_SIGNAL_FAIL_ID = 12,
	WS_ETH_LAYER_FAULT_ID = 0,


};



#endif /* FAULTIDS_H_ */
